"""GirlBot CLI - Command-line interface for setup and management.

Usage:
    girlbot init      Interactive setup wizard
    girlbot run       Start the bot
    girlbot check     Validate configuration and connectivity
    girlbot features  List available/enabled features
    girlbot status    Show service health status
"""

import asyncio
import os
import sys
from pathlib import Path
from typing import Any

import click
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.prompt import Prompt, Confirm

console = Console()

# Feature definitions
FEATURES = {
    "stylist": {
        "name": "AI Stylist",
        "description": "Outfit analysis, color season discovery, wardrobe management",
        "required_keys": ["OPENAI_API_KEY"],
        "optional_keys": [],
        "default": True,
    },
    "fitness": {
        "name": "Fitness Discovery",
        "description": "Find gyms, yoga studios, fitness classes nearby",
        "required_keys": ["GOOGLE_PLACES_API_KEY"],
        "optional_keys": [],
        "default": False,
    },
    "travel": {
        "name": "Travel Planning",
        "description": "Flight search, hotel booking, trip planning",
        "required_keys": ["AMADEUS_CLIENT_ID", "AMADEUS_CLIENT_SECRET"],
        "optional_keys": ["HOTELBEDS_API_KEY", "HOTELBEDS_SECRET"],
        "default": False,
    },
}


def get_env_path() -> Path:
    """Get the path to the .env file."""
    return Path.cwd() / ".env"


def get_user_config_path() -> Path:
    """Get the path to user config directory."""
    if sys.platform == "win32":
        base = Path(os.environ.get("APPDATA", Path.home()))
    else:
        base = Path.home() / ".config"
    return base / "girlbot"


def load_env_file(path: Path) -> dict[str, str]:
    """Load environment variables from a file."""
    env = {}
    if path.exists():
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    env[key.strip()] = value.strip().strip("'\"")
    return env


def save_env_file(path: Path, env: dict[str, str], append: bool = False) -> None:
    """Save environment variables to a file."""
    mode = "a" if append else "w"
    with open(path, mode) as f:
        if not append:
            f.write("# GirlBot Configuration\n")
            f.write("# Generated by 'girlbot init'\n\n")
        for key, value in env.items():
            f.write(f"{key}={value}\n")


def check_api_key_format(key: str, value: str) -> tuple[bool, str]:
    """Validate API key format."""
    if not value:
        return False, "Empty value"

    if key == "TELEGRAM_BOT_TOKEN":
        if ":" not in value or len(value) < 40:
            return False, "Invalid format (should be like 123456789:ABC...)"
        return True, "Format OK"

    if key == "OPENAI_API_KEY":
        if not value.startswith("sk-"):
            return False, "Should start with 'sk-'"
        return True, "Format OK"

    if key == "ANTHROPIC_API_KEY":
        if not value.startswith("sk-ant-"):
            return False, "Should start with 'sk-ant-'"
        return True, "Format OK"

    return True, "OK"


@click.group()
@click.version_option(version="0.1.0", prog_name="GirlBot")
def main():
    """GirlBot - AI Stylist & Wellness Assistant

    A Telegram bot that provides personalized style advice, color analysis,
    fitness discovery, and more.
    """
    pass


@main.command()
@click.option("--force", "-f", is_flag=True, help="Overwrite existing configuration")
def init(force: bool):
    """Interactive setup wizard for GirlBot configuration."""
    console.print(Panel.fit(
        "[bold blue]GirlBot Setup Wizard[/bold blue]\n"
        "This will guide you through configuring your bot.",
        border_style="blue"
    ))

    env_path = get_env_path()
    existing_env = load_env_file(env_path) if env_path.exists() else {}

    if env_path.exists() and not force:
        console.print(f"\n[yellow]Found existing .env file at {env_path}[/yellow]")
        if not Confirm.ask("Do you want to update it?", default=True):
            console.print("[dim]Setup cancelled.[/dim]")
            return

    new_env = {}

    # Step 1: Telegram Bot Token
    console.print("\n[bold]Step 1: Telegram Bot Token[/bold]")
    console.print("[dim]Get this from @BotFather on Telegram (https://t.me/BotFather)[/dim]")

    default_token = existing_env.get("TELEGRAM_BOT_TOKEN", "")
    token = Prompt.ask(
        "Telegram Bot Token",
        default=default_token if default_token else None,
        show_default=bool(default_token)
    )

    valid, msg = check_api_key_format("TELEGRAM_BOT_TOKEN", token)
    if not valid:
        console.print(f"[yellow]Warning: {msg}[/yellow]")
    new_env["TELEGRAM_BOT_TOKEN"] = token

    # Step 2: OpenAI API Key
    console.print("\n[bold]Step 2: OpenAI API Key[/bold]")
    console.print("[dim]Get this from platform.openai.com/api-keys[/dim]")

    default_openai = existing_env.get("OPENAI_API_KEY", "")
    openai_key = Prompt.ask(
        "OpenAI API Key",
        default=default_openai if default_openai else None,
        show_default=bool(default_openai)
    )

    valid, msg = check_api_key_format("OPENAI_API_KEY", openai_key)
    if not valid:
        console.print(f"[yellow]Warning: {msg}[/yellow]")
    new_env["OPENAI_API_KEY"] = openai_key

    # Step 3: Feature Selection
    console.print("\n[bold]Step 3: Feature Selection[/bold]")
    console.print("[dim]Choose which features to enable[/dim]\n")

    enabled_features = []

    for feature_id, feature in FEATURES.items():
        default_enabled = existing_env.get(f"ENABLE_{feature_id.upper()}", str(feature["default"])).lower() == "true"

        if Confirm.ask(
            f"Enable [cyan]{feature['name']}[/cyan]? ({feature['description']})",
            default=default_enabled
        ):
            enabled_features.append(feature_id)
            new_env[f"ENABLE_{feature_id.upper()}"] = "true"

            # Ask for required keys
            for key in feature["required_keys"]:
                if key not in new_env:
                    console.print(f"\n[dim]{feature['name']} requires {key}[/dim]")
                    default_val = existing_env.get(key, "")
                    value = Prompt.ask(
                        f"  {key}",
                        default=default_val if default_val else None,
                        show_default=bool(default_val)
                    )
                    if value:
                        new_env[key] = value
        else:
            new_env[f"ENABLE_{feature_id.upper()}"] = "false"

    # Step 4: Redis Configuration
    console.print("\n[bold]Step 4: Redis Configuration[/bold]")
    console.print("[dim]Redis is used for session storage. Leave empty for in-memory storage.[/dim]")

    default_redis = existing_env.get("REDIS_URL", "")
    redis_url = Prompt.ask(
        "Redis URL (optional)",
        default=default_redis if default_redis else "redis://localhost:6379",
        show_default=True
    )
    if redis_url:
        new_env["REDIS_URL"] = redis_url

    # Step 5: Environment
    console.print("\n[bold]Step 5: Environment[/bold]")
    default_env = existing_env.get("ENVIRONMENT", "development")
    environment = Prompt.ask(
        "Environment",
        choices=["development", "staging", "production"],
        default=default_env
    )
    new_env["ENVIRONMENT"] = environment
    new_env["DEBUG"] = "true" if environment == "development" else "false"

    # Save configuration
    console.print("\n[bold]Saving configuration...[/bold]")
    save_env_file(env_path, new_env)
    console.print(f"[green]Configuration saved to {env_path}[/green]")

    # Summary
    console.print("\n")
    console.print(Panel(
        f"[bold green]Setup Complete![/bold green]\n\n"
        f"Enabled features: {', '.join(enabled_features) or 'None'}\n"
        f"Environment: {environment}\n\n"
        f"[dim]Next steps:[/dim]\n"
        f"  1. Run [cyan]girlbot check[/cyan] to validate configuration\n"
        f"  2. Run [cyan]girlbot run[/cyan] to start the bot",
        border_style="green"
    ))


@main.command()
def check():
    """Validate configuration and test connectivity."""
    console.print(Panel.fit(
        "[bold blue]GirlBot Configuration Check[/bold blue]",
        border_style="blue"
    ))

    # Load environment
    from dotenv import load_dotenv
    load_dotenv()

    results = []
    all_ok = True

    # Check required configuration
    console.print("\n[bold]Configuration[/bold]")

    # Telegram Token
    token = os.environ.get("TELEGRAM_BOT_TOKEN", "")
    if token:
        valid, msg = check_api_key_format("TELEGRAM_BOT_TOKEN", token)
        if valid:
            results.append(("Telegram Token", "OK", "green", f"...{token[-10:]}"))
        else:
            results.append(("Telegram Token", "INVALID", "yellow", msg))
            all_ok = False
    else:
        results.append(("Telegram Token", "MISSING", "red", "Required - get from @BotFather"))
        all_ok = False

    # OpenAI Key
    openai_key = os.environ.get("OPENAI_API_KEY", "")
    if openai_key:
        valid, msg = check_api_key_format("OPENAI_API_KEY", openai_key)
        if valid:
            results.append(("OpenAI API Key", "OK", "green", f"...{openai_key[-8:]}"))
        else:
            results.append(("OpenAI API Key", "INVALID", "yellow", msg))
    else:
        results.append(("OpenAI API Key", "MISSING", "red", "Required for AI Stylist"))
        all_ok = False

    # Display config results
    table = Table(show_header=True, header_style="bold")
    table.add_column("Setting")
    table.add_column("Status")
    table.add_column("Details")

    for name, status, color, details in results:
        table.add_row(name, f"[{color}]{status}[/{color}]", details)

    console.print(table)

    # Check features
    console.print("\n[bold]Features[/bold]")

    feature_table = Table(show_header=True, header_style="bold")
    feature_table.add_column("Feature")
    feature_table.add_column("Enabled")
    feature_table.add_column("Status")

    for feature_id, feature in FEATURES.items():
        enabled = os.environ.get(f"ENABLE_{feature_id.upper()}", str(feature["default"])).lower() == "true"

        if enabled:
            # Check required keys
            missing = [k for k in feature["required_keys"] if not os.environ.get(k)]
            if missing:
                status = f"[yellow]Missing: {', '.join(missing)}[/yellow]"
            else:
                status = "[green]Ready[/green]"
        else:
            status = "[dim]Disabled[/dim]"

        feature_table.add_row(
            feature["name"],
            "[green]Yes[/green]" if enabled else "[dim]No[/dim]",
            status
        )

    console.print(feature_table)

    # Check connectivity
    console.print("\n[bold]Connectivity[/bold]")

    conn_results = asyncio.run(_check_connectivity())

    conn_table = Table(show_header=True, header_style="bold")
    conn_table.add_column("Service")
    conn_table.add_column("Status")
    conn_table.add_column("Details")

    for name, status, color, details in conn_results:
        conn_table.add_row(name, f"[{color}]{status}[/{color}]", details)
        if status == "FAILED":
            all_ok = False

    console.print(conn_table)

    # Summary
    console.print()
    if all_ok:
        console.print("[bold green]All checks passed! Run 'girlbot run' to start the bot.[/bold green]")
    else:
        console.print("[bold yellow]Some checks failed. Please fix the issues above.[/bold yellow]")
        sys.exit(1)


async def _check_connectivity() -> list[tuple[str, str, str, str]]:
    """Check connectivity to external services."""
    results = []

    # Check Redis
    redis_url = os.environ.get("REDIS_URL", "redis://localhost:6379")
    try:
        import redis.asyncio as redis
        client = redis.from_url(redis_url, socket_timeout=5)
        await client.ping()
        await client.aclose()
        results.append(("Redis", "OK", "green", redis_url.split("@")[-1] if "@" in redis_url else redis_url))
    except Exception as e:
        results.append(("Redis", "UNAVAILABLE", "yellow", f"Will use in-memory cache ({str(e)[:30]})"))

    # Check Telegram API
    token = os.environ.get("TELEGRAM_BOT_TOKEN", "")
    if token:
        try:
            import httpx
            async with httpx.AsyncClient(timeout=10) as client:
                resp = await client.get(f"https://api.telegram.org/bot{token}/getMe")
                if resp.status_code == 200:
                    data = resp.json()
                    bot_name = data.get("result", {}).get("username", "unknown")
                    results.append(("Telegram API", "OK", "green", f"@{bot_name}"))
                else:
                    results.append(("Telegram API", "FAILED", "red", f"HTTP {resp.status_code}"))
        except Exception as e:
            results.append(("Telegram API", "FAILED", "red", str(e)[:40]))

    # Check OpenAI API
    openai_key = os.environ.get("OPENAI_API_KEY", "")
    if openai_key:
        try:
            import httpx
            async with httpx.AsyncClient(timeout=10) as client:
                resp = await client.get(
                    "https://api.openai.com/v1/models",
                    headers={"Authorization": f"Bearer {openai_key}"}
                )
                if resp.status_code == 200:
                    results.append(("OpenAI API", "OK", "green", "Connected"))
                elif resp.status_code == 401:
                    results.append(("OpenAI API", "FAILED", "red", "Invalid API key"))
                else:
                    results.append(("OpenAI API", "FAILED", "yellow", f"HTTP {resp.status_code}"))
        except Exception as e:
            results.append(("OpenAI API", "FAILED", "red", str(e)[:40]))

    return results


@main.command()
def features():
    """List available features and their status."""
    from dotenv import load_dotenv
    load_dotenv()

    console.print(Panel.fit(
        "[bold blue]GirlBot Features[/bold blue]",
        border_style="blue"
    ))

    for feature_id, feature in FEATURES.items():
        enabled = os.environ.get(f"ENABLE_{feature_id.upper()}", str(feature["default"])).lower() == "true"

        # Check required keys
        missing_keys = [k for k in feature["required_keys"] if not os.environ.get(k)]

        status_icon = "[green]ON[/green]" if enabled else "[dim]OFF[/dim]"
        if enabled and missing_keys:
            status_icon = "[yellow]PARTIAL[/yellow]"

        console.print(f"\n{status_icon} [bold]{feature['name']}[/bold]")
        console.print(f"   [dim]{feature['description']}[/dim]")

        if enabled:
            console.print(f"   [dim]Toggle: ENABLE_{feature_id.upper()}=false[/dim]")
            if missing_keys:
                console.print(f"   [yellow]Missing keys: {', '.join(missing_keys)}[/yellow]")
        else:
            console.print(f"   [dim]Toggle: ENABLE_{feature_id.upper()}=true[/dim]")
            if feature["required_keys"]:
                console.print(f"   [dim]Requires: {', '.join(feature['required_keys'])}[/dim]")


@main.command()
def status():
    """Show service health status (circuit breakers, rate limiters)."""
    from dotenv import load_dotenv
    load_dotenv()

    console.print(Panel.fit(
        "[bold blue]GirlBot Service Health[/bold blue]",
        border_style="blue"
    ))

    try:
        from src.services.resilience import get_all_service_health, CircuitState

        health = get_all_service_health()

        if not health:
            console.print("\n[dim]No services have been used yet.[/dim]")
            return

        table = Table(show_header=True, header_style="bold")
        table.add_column("Service")
        table.add_column("Circuit State")
        table.add_column("Healthy")
        table.add_column("Failures")

        for svc in health:
            if svc.circuit_state == CircuitState.CLOSED:
                state_display = "[green]CLOSED[/green]"
            elif svc.circuit_state == CircuitState.OPEN:
                state_display = "[red]OPEN[/red]"
            else:
                state_display = "[yellow]HALF-OPEN[/yellow]"

            healthy_display = "[green]Yes[/green]" if svc.is_healthy else "[red]No[/red]"

            table.add_row(
                svc.name,
                state_display,
                healthy_display,
                str(svc.failure_count)
            )

        console.print(table)

    except ImportError:
        console.print("[yellow]Resilience module not loaded. Run the bot first.[/yellow]")


@main.command()
@click.option("--debug", "-d", is_flag=True, help="Enable debug logging")
def run(debug: bool):
    """Start the GirlBot Telegram bot."""
    from dotenv import load_dotenv
    load_dotenv()

    # Override debug if flag is set
    if debug:
        os.environ["DEBUG"] = "true"
        os.environ["LOG_LEVEL"] = "DEBUG"

    console.print(Panel.fit(
        "[bold blue]Starting GirlBot[/bold blue]",
        border_style="blue"
    ))

    # Validate minimum configuration
    if not os.environ.get("TELEGRAM_BOT_TOKEN"):
        console.print("[red]Error: TELEGRAM_BOT_TOKEN not set[/red]")
        console.print("[dim]Run 'girlbot init' to configure, or set the environment variable.[/dim]")
        sys.exit(1)

    if not os.environ.get("OPENAI_API_KEY"):
        console.print("[red]Error: OPENAI_API_KEY not set[/red]")
        console.print("[dim]Run 'girlbot init' to configure, or set the environment variable.[/dim]")
        sys.exit(1)

    # Import and run
    try:
        from src.bot.app import create_bot_application
        from src.config.logging import get_logger
        from src.config import settings

        logger = get_logger(__name__)
        logger.info(
            "starting_girlbot",
            environment=settings.environment,
            debug=settings.debug,
            llm_model=settings.openai_model_primary,
        )

        app = create_bot_application()

        console.print(f"[green]Bot starting in {settings.environment} mode...[/green]")
        console.print("[dim]Press Ctrl+C to stop.[/dim]\n")

        app.run_polling(drop_pending_updates=True)

    except KeyboardInterrupt:
        console.print("\n[yellow]Bot stopped.[/yellow]")
    except Exception as e:
        console.print(f"[red]Error: {e}[/red]")
        if debug:
            import traceback
            traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
